language: python

install:
  - pip install -r xblog/requirements.txt

script:
  - python runtests.py

deploy:
  provider: pypi
  user: rubeon
  password:
    secure: fA+ca7HUr7AcnYdhykIOymllNMnei7rZD/0PB+E0TKnz/kyBJ0j2TilqdJHbMDRSGScluGgNq1o754HyKfSqplVUoRvw8XTgkcqVZQGADq8Xj0VxiLsb/D7JxYRCaDPfK1m+UpcgRcbV+X/sVBnJEi1/TN93B0R49mpYkO2Uk91hKspmBOmmCYyqHyIJF7pFus+XEvX3AHAh3tfZ6jwZ/uOxyq03a3HMHwrIUEq530EHuP8NScoG2tifQmGJRmiiAdg7C425bwd05bxt/kgdEocGRxiCigp8sHu7dEalHXlkwJExLHTViEWfKIlWmikJxu5rGzJ/Pa9LHhkqwATqiV33twnujxZ60Ct2906WBqvD/iFa+vnehgZZId+W7Oxci6day7SqfX7PtP3u/W1gD5k49tkV/Zlh69UW2dSh+ANR2GD71C5lL2UqR1b1QId72SLGKIjoR25N7uL7vsQsXwcQjxrPToVHtTO4R1YlvLyHQnMXN924J/hkjdnWnepeKTruvWK07pajmWytrnSYDHJASDjlnUEYH2wfvhWhhAlHJADZxZA6mOQ2cW6xOplItShZVOMRnE+6cg/ndY28N3rRAxyNwkfs2EmdgQuiTdzdZJ0CvTxrF+lcwhuH8Fmm6zJM7gjh1Dtql53d0WdWoDvrypC3ae8jljVO4ceSmqk=
  on:
    tags: true
