# Generated by Django 5.2 on 2025-04-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='default_comments_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='default_ping_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='enable_pings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('post', 'Post'), ('page', 'Page')], default='post', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='sticky',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('publish', 'Published'), ('private', 'Private'), ('trash', 'Trash')], default='Draft', max_length=32, null=True),
        ),
    ]
