name: Run Python Tests

on:
  push:
    branches:
      - '**'  # Matches all branches
  pull_request:
    branches:
      - '**'  # Matches all branches

jobs:
  test:
    strategy:
      matrix:
        python_version:
          - '3.9'
          - '3.10'
          - '3.11'
        django_version:
          - '<4'
          - '<5'
          - '>=5,<6'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}  # Adjust to your Python version
          cache: 'pip'  # Cache pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "django${{ matrix.django_version }}"
          pip install -r xblog/requirements.txt  # Adjust if you have a requirements file

      - name: Run tests
        run: python runtests.py
