name: Bump Version on Merge to Master

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install bump-my-version
        run: |
          python -m pip install --upgrade pip
          pip install bump-my-version

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Get PR labels
        id: pr-labels
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request?.number || (await github.rest.repos.listPullRequestsAssociatedWithCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: context.sha
              })).data[0]?.number
            });
            return pr.data.labels.map(label => label.name);
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine bump type
        id: bump-type
        run: |
          labels=$(echo '${{ steps.pr-labels.outputs.result }}' | jq -r 'join(",")')
          if [[ "$labels" == *"minor"* ]]; then
            echo "bump_type=minor" >> $GITHUB_OUTPUT
          else
            echo "bump_type=patch" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version
        run: |
          bump-my-version bump ${{ steps.bump-type.outputs.bump_type }}

      - name: Push changes and tags
        run: |
          git push origin master
          git push origin --tags
          
